# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ee9b89948bdb6892150db05fe6030ca12217468b272f1f5b6e9816c219dc519f173d3fa65489d8db3c501311ee6cad56fd49970d19f1d15df7052889786ecb8

test:
  secret_key_base: c02cf6e21179f361edacd15364b05b6bc496afed090809a3028fb98587289923552ae74e394fb72cf61bb5e888b7bca773747266ab833adfd5691324f17c5e13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
